server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
components:
  database:
    driver: mysql
    dns: root:root@tcp(127.0.0.1:3306)/dddgo?parseTime=True&loc=Local
    debug: true
  redis:
    addr: 127.0.0.1:6379
    db: 0
  event:
    type: memory
    bufferSize: 100
