logging:
  level: ${LOG_LEVEL:info}
trace:
  endpoint: ${TRACE_ENDPOINT:http://127.0.0.1:14268/api/traces}
server:
  http:
    addr: ${SERVER_HTTP_ADDR:0.0.0.0:8000}
    timeout: 1s
  grpc:
    addr: ${SERVER_GRPC_ADDR:0.0.0.0:9000}
    timeout: 1s
auth:
  key: ${AUTH_KEY:abcdefg}
components:
  database:
    driver: ${DATABASE_DRIVER:mysql}
    dns: ${DATABASE_DNS:root:root@tcp(127.0.0.1:3306)/dddgo?parseTime=True&loc=Local}
    debug: ${DATABASE_DEBUG:false}
  redis:
    addr: ${REDIS_ADDR:127.0.0.1:6379}
    db: ${REDIS_DB:0}
  event:
    type: ${EVENT_TYPE:memory}
    bufferSize: ${EVENT_BUFFER_SIZE:100}

