// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/ofavor/kratos-layout/internal/application"
	"github.com/ofavor/kratos-layout/internal/conf"
	"github.com/ofavor/kratos-layout/internal/infrastructure"
	"github.com/ofavor/kratos-layout/internal/infrastructure/repo"
	"github.com/ofavor/kratos-layout/internal/interfaces"
	"go.opentelemetry.io/otel/sdk/trace"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, registry *conf.Registry, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	eventBus := infrastructure.NewEvent(bootstrap)
	database := infrastructure.NewDatabase(bootstrap)
	greeterRepo := repo.NewGreeterRepo(database)
	greeterAppService := application.NewGreeterAppService(logger, eventBus, greeterRepo)
	server := interfaces.NewGRPCServer(logger, tracerProvider, bootstrap, greeterAppService)
	httpServer := interfaces.NewHTTPServer(logger, tracerProvider, bootstrap, greeterAppService)
	eventHandler := interfaces.NewEventHandler(logger, eventBus, greeterAppService)
	cache := infrastructure.NewCache(bootstrap)
	infra := infrastructure.NewInfra(database, cache, eventBus)
	app := newApp(logger, server, httpServer, eventHandler, infra)
	return app, func() {
	}, nil
}
